#!/bin/bash

zfs_versions=0.8.1
userland_only=false
kernel_releases=
src_dir=$PWD/src
out_dir=$PWD/out
archive_dir=$out_dir/archive
build_dir=$out_dir/build
zfs_builder=delphix/zfs-builder:latest

function usage() {
  echo "Usage: $0 [-u] [kernel_release ...]" 1>&2
  exit 2
}

function die() {
  echo $* 1>&2
  exit 1
}

while getopts ":uz:" o; do
  case "${o}" in
    u)
      userland_only=true
      ;;
    z)
      zfs_versions=$OPTARG
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))
kernel_releases=$*
[[ -z $kernel_releases ]] && kernel_releases=$(ls -1 $src_dir)

mkdir -p $archive_dir || exit 1
mkdir -p $build_dir || exit 1
for version in $zfs_versions; do
  echo "Building ZFS version $version"
  first=true
  for release in $kernel_releases; do
    echo "Building kernel version $release"
    [[ -d $src_dir/$release ]] || die "Unknown kernel release $release"
    [[ -f $src_dir/$release/uname ]] || die "Missing uname file for $release"

    if [[ $userland_only = true ]]; then
      zfs_config=user
    elif [[ $first = true ]]; then
      zfs_config=all
    else
      zfs_config=kernel
    fi

    mkdir -p $build_dir/$release || exit 1
    echo docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
      -e ZFS_VERSION=zfs-$version -e KERNEL_RELEASE=$release \
      -e KERNEL_UNAME="$(cat $src_dir/$release/uname)" -e ZFS_CONFIG=$zfs_config \
      -v $src_dir/$release:/config -v $build_dir/$release:/build \
      $zfs_builder || exit 1

    cd $build_dir/$release
    if [[ $zfs_config != kernel ]]; then
      echo "Creating userland archive zfs-$version-userland.tar.gz"
      tar -czf $archive_dir/zfs-$version-userland.tar.gz \
        --exclude lib/modules --exclude lib/udev --exclude "lib/libzpool.*" \
        --exclude sbin/zdb --exclude sbin/ztest sbin lib || exit 1
    fi

    first=false
    [[ $userland_only = true ]] && break

    echo "Creating kernel archive zfs-$version-$release.tar.gz"
    tar -czf $archive_dir/zfs-$version-$release.tar.gz lib/modules || exit 1
  done
done
exit 0
