FROM ubuntu:22.04

RUN apt update && apt install -y build-essential cmake zlib1g-dev libcppunit-dev git wget curl

# Install OpenSSL 1.1.1
RUN wget https://www.openssl.org/source/openssl-1.1.1s.tar.gz -O - | tar -xz
WORKDIR /openssl-1.1.1s
RUN ./config
RUN make && make install
RUN ldconfig /usr/local/lib64/ && echo "/usr/local/lib64" > /etc/ld.so.conf.d/openssl.conf

# Install ZFS Reqs
RUN apt install -y xz-utils  autoconf automake libtool gawk alien fakeroot dkms \
    libblkid-dev uuid-dev libudev-dev libssl-dev zlib1g-dev libaio-dev          \
    libattr1-dev libelf-dev python3 python3-dev python3-setuptools              \
    python3-cffi libffi-dev python3-packaging

# Copy Build Scripts to Image
COPY build_docker.sh /
COPY publish /

#Install AWS CLI
RUN apt install -y unzip
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install

WORKDIR /src